name: Build Next.js UI and Upload as Release

on:
  pull_request:
    branches:
      - main
    types:
      - merged
  workflow_dispatch:
    
jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.1.0'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Next.js project (static export)
      - name: Build Next.js project
        run: npm run build
        env:
          NEXT_PUBLIC_BUILD_DIR: out 
          NEXT_PUBLIC_MAPBOX_API_KEY: ${{ secrets.NEXT_PUBLIC_MAPBOX_API_KEY }}

      # Step 6: Create a zip file of the exported static output
      - name: Zip static output
        run: |
          zip -r ./ui-static.zip ./out
          tar czf ./ui-static.tar.gz ./out 

      # Step 7: Get the latest commit hash
      - name: Get latest commit hash
        id: get_commit_hash
        run: |
          commit_hash=$(git rev-parse --short HEAD)
          echo "Commit hash: $commit_hash"
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

      # Step 8: Create a Git tag based on the commit hash
      - name: Create Git tag for the release
        run: |
          git tag ${{ env.commit_hash }}
          git push origin ${{ env.commit_hash }}
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_UI_RELEASES }}

      # Step 9: Create a GitHub release and upload assets
      - name: Create a GitHub release and upload assets
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: |
            ui-static.zip
            ui-static.tar.gz
        env:
          GITHUB_RELEASE_TAG: ${{ env.commit_hash }}  
          GITHUB_TOKEN: ${{ secrets.ADD_TO_UI_RELEASES }}
